[package]
name = "srx"
version = "0.2.0"
edition = "2021"

[profile.release]
debug = true
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
